import { useState } from 'react';
import { Link, NavLink, useNavigate } from 'react-router-dom';
import { Avatar, Button } from './ui';

function rolesFromSession(): string[] { if (typeof window === 'undefined') return []; try { const token = window.localStorage.getItem('accessToken'); return token ? (JSON.parse(atob(token.split('.')[1].replace(/-/g, '+').replace(/_/g, '/'))).roles as string[]) : []; } catch { return []; } }
function CourtinMark() { return <span aria-hidden className="grid h-8 w-8 place-items-center rounded-lg bg-brand-yellow font-display text-lg font-extrabold text-brand-navy">×</span>; }
const navItems = [{ to: '/venues', label: 'Đặt sân' }, { to: '/matches', label: 'Tìm kèo' }, { to: '/community', label: 'Cộng đồng' }] as const;

export function Navbar({ onOpenAuth, sessionVersion }: { onOpenAuth: () => void; sessionVersion?: number }) {
  const [menuOpen, setMenuOpen] = useState(false); const [accountOpen, setAccountOpen] = useState(false); const navigate = useNavigate(); const roles = rolesFromSession(); const isSignedIn = roles.length > 0;
  const logout = () => { window.localStorage.removeItem('accessToken'); window.localStorage.removeItem('refreshToken'); window.localStorage.removeItem('roles'); navigate('/'); setAccountOpen(false); };
  const linkClass = ({ isActive }: { isActive: boolean }) => `rounded-full px-3 py-2 text-xs font-bold uppercase tracking-[0.05em] transition ${isActive ? 'bg-surface/15 text-brand-yellow' : 'text-surface/70 hover:text-surface'}`;
  return <header className="sticky top-0 z-50 bg-brand-navy text-surface shadow-[0_1px_3px_rgb(21_68_108_/_18%)]"><div className="page-container flex h-16 items-center justify-between gap-3 sm:h-20"><Link to="/" aria-label="COURTIN - trang chủ" className="flex items-center gap-2 text-surface"><CourtinMark /><span className="font-display text-xl font-extrabold tracking-[-0.04em]">COURTIN</span></Link><nav className="hidden items-center gap-2 md:flex" aria-label="Điều hướng chính"><NavLink to="/" end className={linkClass}>Trang chủ</NavLink>{navItems.map((item) => <NavLink key={item.to} to={item.to} className={linkClass}>{item.label}</NavLink>)}</nav><div className="flex items-center gap-2" data-session-version={sessionVersion}>{isSignedIn ? <div className="relative"><button type="button" aria-label="Mở menu tài khoản" aria-expanded={accountOpen} onClick={() => setAccountOpen((open) => !open)} className="rounded-full border border-surface/20 p-1"><Avatar /></button>{accountOpen && <div className="absolute right-0 mt-3 w-52 rounded-2xl border border-line bg-surface p-2 text-ink-900 shadow-[var(--shadow-raised)]"><Link className="block rounded-xl px-3 py-2 text-sm font-semibold hover:bg-canvas hover:text-brand-navy" to="/profile" onClick={() => setAccountOpen(false)}>Hồ sơ</Link>{roles.includes('player') && <><Link className="block rounded-xl px-3 py-2 text-sm font-semibold hover:bg-canvas hover:text-brand-navy" to="/passport" onClick={() => setAccountOpen(false)}>Player Passport</Link><Link className="block rounded-xl px-3 py-2 text-sm font-semibold hover:bg-canvas hover:text-brand-navy" to="/assistant" onClick={() => setAccountOpen(false)}>Trợ lý AI</Link></>}{roles.includes('admin') && <Link className="block rounded-xl px-3 py-2 text-sm font-semibold hover:bg-canvas hover:text-brand-navy" to="/admin" onClick={() => setAccountOpen(false)}>Quản trị</Link>}<button type="button" onClick={logout} className="w-full rounded-xl px-3 py-2 text-left text-sm font-semibold text-danger hover:bg-danger-bg">Đăng xuất</button></div>}</div> : <Button size="sm" onClick={onOpenAuth}>Đăng nhập / Đăng ký</Button>}<button type="button" aria-label="Mở menu điều hướng" aria-expanded={menuOpen} onClick={() => setMenuOpen((open) => !open)} className="grid h-10 w-10 place-items-center rounded-full border border-surface/30 text-lg text-surface md:hidden"><span aria-hidden>☰</span></button></div></div>{menuOpen && <nav className="border-t border-surface/15 bg-brand-navy px-4 py-3 md:hidden" aria-label="Điều hướng di động"><NavLink to="/" end onClick={() => setMenuOpen(false)} className={linkClass}>Trang chủ</NavLink>{navItems.map((item) => <NavLink key={item.to} to={item.to} onClick={() => setMenuOpen(false)} className={`${linkClass({ isActive: false })} block`}>{item.label}</NavLink>)}</nav>}</header>;
}
