import { useEffect, useRef, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useNotifications } from '../notifications/NotificationProvider.js';
import { useSession } from '../session/SessionProvider.js';
import { resolveNotificationRoute } from '../notifications/notificationRoutes.js';
export function NotificationBell({ onOpenChange }: { onOpenChange?: (open: boolean) => void }) {
  const { session, setActiveRole } = useSession(); const { recent, unreadCount, markRead, markAllRead } = useNotifications(); const [open, setOpen] = useState(false); const ref = useRef<HTMLDivElement>(null); const navigate = useNavigate();
  const setVisible = (value: boolean) => { setOpen(value); onOpenChange?.(value); };
  useEffect(() => { const close = (event: MouseEvent) => { if (!ref.current?.contains(event.target as Node)) setVisible(false); }; const key = (event: KeyboardEvent) => { if (event.key === 'Escape') setVisible(false); }; document.addEventListener('mousedown', close); document.addEventListener('keydown', key); return () => { document.removeEventListener('mousedown', close); document.removeEventListener('keydown', key); }; }, []);
  if (!session) return null;
  const click = (id: string, route: string | null, targetRole: typeof session.activeRole) => { void markRead(id).catch(() => undefined); setVisible(false); if (session.roles.includes(targetRole)) setActiveRole(targetRole); if (route) navigate(route); };
  return <div ref={ref} className="relative"><button type="button" aria-label="Thông báo" aria-expanded={open} onClick={() => setVisible(!open)} className="relative grid h-10 w-10 place-items-center rounded-full text-surface/90 hover:bg-surface/10 focus-visible:ring-2 focus-visible:ring-brand-yellow"><svg viewBox="0 0 24 24" className="h-5 w-5" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M10 21h4"/></svg>{unreadCount > 0 && <span className="absolute -right-1 -top-1 grid min-w-5 h-5 place-items-center rounded-full border-2 border-brand-navy bg-danger px-1 text-[10px] font-extrabold text-surface">{unreadCount > 99 ? '99+' : unreadCount}</span>}</button>{open && <section className="absolute right-0 mt-2 w-[min(24rem,calc(100vw-2rem))] overflow-hidden rounded-2xl border border-line bg-surface text-ink-900 shadow-xl"><header className="flex items-center justify-between border-b border-line px-4 py-3"><strong>Thông báo{unreadCount ? <span className="ml-2 rounded-full bg-green-50 px-2 py-1 text-xs text-green-700">{unreadCount} mới</span> : null}</strong><button className="text-xs font-bold text-brand-navy disabled:opacity-50" disabled={!unreadCount} onClick={() => void markAllRead()}>Đã đọc tất cả</button></header>{recent.length ? <div>{recent.filter((row) => row.priority === 'action_required').length ? <p className="px-4 pt-3 text-[11px] font-bold uppercase tracking-wide text-ink-500">Cần bạn xử lý</p> : null}{recent.map((row) => <button key={row.id} onClick={() => click(row.id, resolveNotificationRoute(row, row.targetRole), row.targetRole)} className={`block w-full border-b border-line px-4 py-3 text-left hover:bg-canvas ${row.readAt ? '' : 'bg-green-50/50'}`}><p className="text-sm font-bold">{row.title} <span className="text-xs font-semibold text-ink-500">· {row.targetRole === 'provider' ? 'Chủ sân' : row.targetRole === 'admin' ? 'Quản trị viên' : 'Người chơi'}</span></p><p className="mt-1 text-xs text-ink-500">{row.body}</p></button>)}</div> : <p className="p-5 text-center text-sm text-ink-500">Bạn chưa có thông báo nào.</p>}<Link to="/notifications" onClick={() => setVisible(false)} className="block p-3 text-center text-sm font-bold text-brand-navy hover:bg-canvas">Xem toàn bộ lịch sử →</Link></section>}</div>;
}
