-- AlterTable
ALTER TABLE "bookings" ALTER COLUMN "startAt" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "endAt" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "closures" ALTER COLUMN "date" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "holds" ALTER COLUMN "startAt" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "endAt" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "expiresAt" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "outbox" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "publishedAt" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "pricing_rules" ALTER COLUMN "effectiveFrom" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "processed_events" ALTER COLUMN "processedAt" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "providers" ALTER COLUMN "decidedAt" SET DATA TYPE TIMESTAMPTZ(3);

