import { useCallback, useEffect, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { Button, EmptyState, Pagination, SurfaceCard } from '../components/ui.js';
import { getNotificationPreferences, getNotifications, saveNotificationPreference, type NotificationItem, type NotificationPage } from '../lib/notificationApi.js';
import { useSession } from '../session/SessionProvider.js';
import { useNotifications } from '../notifications/NotificationProvider.js';
import { resolveNotificationRoute } from '../notifications/notificationRoutes.js';
import { useNavigate } from 'react-router-dom';

const labels: Record<string, string> = { booking: 'Đặt sân', finance: 'Tài chính', match: 'Kèo', dispute: 'Tranh chấp', support: 'Hỗ trợ', security: 'Tài khoản & bảo mật', community: 'Cộng đồng' };
export function NotificationsPage() {
  const { session, setActiveRole } = useSession(); const { markRead, refresh } = useNotifications(); const [params, setParams] = useSearchParams(); const navigate = useNavigate(); const [data, setData] = useState<NotificationPage | null>(null); const [error, setError] = useState(''); const [preferences, setPreferences] = useState<{ targetRole: 'player' | 'provider' | 'admin'; category: string; enabled: boolean }[]>([]); const [settings, setSettings] = useState(false);
  const page = Math.max(1, Number(params.get('page') ?? '1') || 1); const role = params.get('role') ?? ''; const unread = params.get('unread') === 'true';
  const load = useCallback(async () => { try { setError(''); const [next, prefs] = await Promise.all([getNotifications({ page, role: role || undefined, unread }), getNotificationPreferences()]); setData(next); setPreferences(prefs.items); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Không thể tải thông báo.'); } }, [page, role, unread]);
  useEffect(() => { void load(); }, [load]);
  const update = (next: Record<string, string | undefined>) => { const query = new URLSearchParams(); if (next.role) query.set('role', next.role); if (next.unread === 'true') query.set('unread', 'true'); if (next.page && next.page !== '1') query.set('page', next.page); setParams(query); };
  const open = (item: NotificationItem) => { void markRead(item.id).then(refresh).catch(() => undefined); if (session!.roles.includes(item.targetRole)) setActiveRole(item.targetRole); const route = resolveNotificationRoute(item, item.targetRole); if (route) navigate(route); };
  return <main className="page-container py-8 sm:py-12"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-h1">Tất cả thông báo</h1><p className="mt-2 text-ink-500">Theo dõi các cập nhật quan trọng trên tài khoản COURTIN.</p></div><Button tone="secondary" onClick={() => setSettings(!settings)}>Cài đặt thông báo</Button></div>{settings && <SurfaceCard className="mt-5"><h2 className="text-h3">Nhóm thông báo</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{preferences.map((pref) => <label key={`${pref.targetRole}-${pref.category}`} className="flex items-center justify-between gap-3 rounded-xl border border-line p-3 text-sm"><span>{labels[pref.category] ?? pref.category} · {pref.targetRole === 'provider' ? 'Chủ sân' : pref.targetRole === 'admin' ? 'Quản trị viên' : 'Người chơi'}</span><input type="checkbox" checked={pref.enabled} disabled={pref.category === 'security'} onChange={(event) => void saveNotificationPreference({ ...pref, enabled: event.target.checked }).then(() => void load())} /></label>)}</div></SurfaceCard>}<div className="mt-6 flex flex-wrap gap-2"><Button size="sm" tone={!role && !unread ? 'primary' : 'secondary'} onClick={() => update({})}>Tất cả</Button><Button size="sm" tone={unread ? 'primary' : 'secondary'} onClick={() => update({ unread: unread ? undefined : 'true' })}>Chưa đọc{data?.unreadCount ? ` · ${data.unreadCount}` : ''}</Button>{session?.roles.map((value) => <Button key={value} size="sm" tone={role === value ? 'primary' : 'secondary'} onClick={() => update({ role: role === value ? undefined : value })}>{value === 'provider' ? 'Chủ sân' : value === 'admin' ? 'Quản trị viên' : 'Người chơi'}</Button>)}</div>{error ? <SurfaceCard className="mt-6"><p role="alert">{error}</p><Button className="mt-3" onClick={() => void load()}>Thử lại</Button></SurfaceCard> : !data ? <p className="mt-6 text-ink-500">Đang tải thông báo…</p> : data.items.length ? <><SurfaceCard className="mt-6 !p-0"><ul>{data.items.map((item) => <li key={item.id}><button className={`w-full border-b border-line px-5 py-4 text-left last:border-0 hover:bg-canvas ${item.readAt ? '' : 'border-l-4 border-l-brand-yellow bg-green-50/40'}`} onClick={() => open(item)}><div className="flex justify-between gap-3"><strong>{item.title}</strong><time className="shrink-0 text-xs text-ink-500">{new Date(item.createdAt).toLocaleString('vi-VN')}</time></div><p className="mt-1 text-sm text-ink-500">{item.body}</p></button></li>)}</ul></SurfaceCard><div className="mt-5"><Pagination page={data.page} pageCount={data.totalPages} onChange={(next) => update({ role: role || undefined, unread: unread ? 'true' : undefined, page: String(next) })} /></div></> : <div className="mt-6"><EmptyState title="Chưa có thông báo phù hợp" description="Thử thay đổi bộ lọc để xem các cập nhật khác." action={<Button tone="secondary" onClick={() => update({})}>Xóa bộ lọc</Button>} /></div>}</main>;
}
