import { useCallback, useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Modal, SurfaceCard, TextInput } from '../../components/ui';
import { addManagedCourt, authorizeVenueImage, getMyManagedVenue, replaceOperatingHours, saveBookingRule, savePricing, updateManagedCourt, updateManagedVenue, uploadVenueImage, type ManagedCourt, type ManagedVenue } from '../../lib/venueBookingApi';
import { ImageUploadPicker, type UploadImageState } from '../../components/CommunityComposer';
import { RouteState } from '../../components/RouteState.js';
import { LocationPicker } from '../../components/map/LocationPicker';

const SUGGESTED_AMENITIES = ['Wi-Fi', 'Bãi giữ xe', 'Nước uống', 'Phòng thay đồ', 'Nhà vệ sinh'] as const;
const WEEKDAYS = ['CN', 'Thứ 2', 'Thứ 3', 'Thứ 4', 'Thứ 5', 'Thứ 6', 'Thứ 7'] as const;
const VND = new Intl.NumberFormat('vi-VN');
interface CourtDraft { id: string; name: string; weekdays: number[]; openTime: string; closeTime: string; hourlyPrice: string; effectiveFrom: string; imageKeys: string[] }
interface VenueDraft { name: string; address: string; lat: number; lng: number; amenities: string[]; imageKeys: string[]; courts: CourtDraft[] }

const minuteToTime = (minute: number) => `${Math.floor(minute / 60).toString().padStart(2, '0')}:${(minute % 60).toString().padStart(2, '0')}`;
const toMinutes = (value: string) => { const [hour, minute] = value.split(':').map(Number); return hour * 60 + minute; };
const formatVnd = (value: string) => value ? `${VND.format(Number(value))} VNĐ` : '';
const same = (a: unknown, b: unknown) => JSON.stringify(a) === JSON.stringify(b);
const keyOf = (item: unknown) => typeof item === 'string' ? item : item && typeof item === 'object' && 'objectKey' in item ? String((item as { objectKey: unknown }).objectKey) : null;
const urlOf = (item: unknown) => typeof item === 'string' && /^(?:https?:\/\/|\/)/.test(item) ? item : item && typeof item === 'object' && 'url' in item ? String((item as { url: unknown }).url) : null;

function courtDraft(court: ManagedCourt): CourtDraft {
  const hours = [...court.operatingHours].sort((a, b) => a.weekday - b.weekday);
  const latest = Math.max(0, ...court.pricingRules.map((item) => item.version));
  const price = court.pricingRules.find((item) => item.version === latest) ?? court.pricingRules[0];
  return { id: court.id, name: court.name, weekdays: hours.map((item) => item.weekday), openTime: minuteToTime(hours[0]?.openMinute ?? 480), closeTime: minuteToTime(hours[0]?.closeMinute ?? 1320), hourlyPrice: price?.price ?? '100000', effectiveFrom: price?.effectiveFrom?.slice(0, 10) ?? new Date().toISOString().slice(0, 10), imageKeys: court.images.map((item) => item.objectKey) };
}
function venueDraft(venue: ManagedVenue): VenueDraft {
  return { name: venue.name, address: venue.address, lat: venue.lat, lng: venue.lng, amenities: Array.isArray(venue.amenities) ? venue.amenities.map(String) : [], imageKeys: Array.isArray(venue.images) ? venue.images.flatMap((item) => keyOf(item) ?? []) : [], courts: venue.courts.map(courtDraft) };
}

export function ManageVenueDetailPage() {
  const { venueId = '' } = useParams();
  const [source, setSource] = useState<ManagedVenue>(); const [original, setOriginal] = useState<VenueDraft>(); const [draft, setDraft] = useState<VenueDraft>();
  const [editing, setEditing] = useState(false); const [confirming, setConfirming] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const [venueUploads, setVenueUploads] = useState<UploadImageState[]>([]); const [courtUploads, setCourtUploads] = useState<Record<string, UploadImageState[]>>({}); const [pickerVersion, setPickerVersion] = useState(0);
  const load = useCallback(async () => { try { const next = await getMyManagedVenue(venueId); const mapped = venueDraft(next); setSource(next); setOriginal(mapped); setDraft(mapped); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Không thể tải cơ sở.'); } }, [venueId]);
  useEffect(() => { void load(); }, [load]);
  const uploaded = (items: UploadImageState[]) => items.filter((item) => item.status === 'uploaded').map((item) => item.objectKey!);
  const allUploads = useMemo(() => [...venueUploads, ...Object.values(courtUploads).flat()], [venueUploads, courtUploads]);
  const changes = useMemo(() => { if (!draft || !original) return []; const list: string[] = []; if (draft.name !== original.name) list.push(`Tên cơ sở: “${original.name}” → “${draft.name}”`); if (draft.address !== original.address) list.push('Địa chỉ cơ sở'); if (draft.lat !== original.lat || draft.lng !== original.lng) list.push('Vị trí bản đồ'); if (!same(draft.amenities, original.amenities)) list.push('Danh sách tiện ích'); if (!same(draft.imageKeys, original.imageKeys) || uploaded(venueUploads).length) list.push('Ảnh cơ sở'); for (const court of draft.courts) { const before = original.courts.find((item) => item.id === court.id); if (!before) { list.push(`Thêm sân “${court.name}”`); continue; } if (court.name !== before.name) list.push(`${before.name}: đổi tên`); if (!same(court.weekdays, before.weekdays) || court.openTime !== before.openTime || court.closeTime !== before.closeTime) list.push(`${court.name}: lịch hoạt động`); if (court.hourlyPrice !== before.hourlyPrice || court.effectiveFrom !== before.effectiveFrom) list.push(`${court.name}: giá`); if (!same(court.imageKeys, before.imageKeys) || uploaded(courtUploads[court.id] ?? []).length) list.push(`${court.name}: ảnh`); } return list; }, [draft, original, venueUploads, courtUploads]);
  if (!draft || !original || !source) return error ? <RouteState variant="error" title="Không thể tải cơ sở" description={error} onRetry={() => void load()} /> : <RouteState variant="loading" title="Đang tải cơ sở kinh doanh" />;

  const patchCourt = (id: string, patch: Partial<CourtDraft>) => setDraft({ ...draft, courts: draft.courts.map((court) => court.id === id ? { ...court, ...patch } : court) });
  const cancel = () => { setDraft(structuredClone(original)); setEditing(false); setConfirming(false); setVenueUploads([]); setCourtUploads({}); setPickerVersion((value) => value + 1); setError(''); };
  const requestSave = () => { if (!draft.name.trim() || !draft.address.trim()) return setError('Tên và địa chỉ cơ sở không được để trống.'); if (allUploads.some((item) => item.status === 'uploading')) return setError('Hãy đợi tất cả ảnh tải xong.'); const today = new Date().toISOString().slice(0, 10); for (const court of draft.courts) { const before = original.courts.find((item) => item.id === court.id); const pricingChanged = !before || before.hourlyPrice !== court.hourlyPrice || before.effectiveFrom !== court.effectiveFrom || !same(before.weekdays, court.weekdays) || before.openTime !== court.openTime || before.closeTime !== court.closeTime; const count = court.imageKeys.length + uploaded(courtUploads[court.id] ?? []).length; if (!court.name.trim() || count < 1 || count > 5 || !court.weekdays.length || toMinutes(court.openTime) >= toMinutes(court.closeTime) || Number(court.hourlyPrice) <= 0) return setError(`Kiểm tra lại tên, ảnh, lịch và giá của ${court.name || 'sân con'}.`); if (pricingChanged && court.effectiveFrom < today) return setError(`Ngày hiệu lực giá mới của ${court.name} không được ở quá khứ.`); } if (!changes.length) return setNotice('Chưa có thay đổi để lưu.'); setError(''); setConfirming(true); };
  const save = async () => { setBusy(true); setError(''); try { await updateManagedVenue(venueId, { name: draft.name.trim(), address: draft.address.trim(), lat: draft.lat, lng: draft.lng, amenities: draft.amenities, images: [...draft.imageKeys, ...uploaded(venueUploads)].map((objectKey) => ({ objectKey })) }); for (const next of draft.courts) { const before = original.courts.find((item) => item.id === next.id); const images = [...next.imageKeys, ...uploaded(courtUploads[next.id] ?? [])]; const entity = before ? null : await addManagedCourt(venueId, next.name.trim(), images.map((objectKey) => ({ objectKey }))); const id = entity?.id ?? next.id; if (before && (before.name !== next.name || !same(before.imageKeys, images))) await updateManagedCourt(id, { name: next.name.trim(), images: images.map((objectKey) => ({ objectKey })) }); const scheduleChanged = !before || !same(before.weekdays, next.weekdays) || before.openTime !== next.openTime || before.closeTime !== next.closeTime; if (scheduleChanged) await replaceOperatingHours(id, next.weekdays.map((weekday) => ({ weekday, openMinute: toMinutes(next.openTime), closeMinute: toMinutes(next.closeTime) }))); const priceChanged = !before || scheduleChanged || before.hourlyPrice !== next.hourlyPrice || before.effectiveFrom !== next.effectiveFrom; if (priceChanged) await savePricing(id, { effectiveFrom: `${next.effectiveFrom}T00:00:00.000Z`, rules: next.weekdays.map((weekday) => ({ weekday, startMinute: toMinutes(next.openTime), endMinute: toMinutes(next.closeTime), price: Number(next.hourlyPrice) })) }); if (!before || scheduleChanged) await saveBookingRule(id, { stepMinutes: 30, minDurationMinutes: 60, maxDurationMinutes: Math.floor((toMinutes(next.closeTime) - toMinutes(next.openTime)) / 30) * 30 }); } setConfirming(false); setEditing(false); setVenueUploads([]); setCourtUploads({}); setPickerVersion((value) => value + 1); await load(); setNotice('Đã lưu các thay đổi của cơ sở.'); } catch (cause) { setConfirming(false); setError(cause instanceof Error ? cause.message : 'Không thể lưu thay đổi.'); } finally { setBusy(false); } };

  const existingVenueImages = Array.isArray(source.images) ? source.images : [];
  return <section className="grid gap-5"><SurfaceCard className="grid gap-4">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-h2">{draft.name}</h2><p className="mt-1 text-sm text-ink-500">{editing ? 'Đang chỉnh sửa — chỉ lưu sau bước xác nhận.' : 'Chế độ chỉ đọc — bấm Sửa để thay đổi.'}</p></div><div className="flex gap-2"><Link to="/manage/venues" className="self-center text-sm font-semibold text-brand-navy">← Danh sách</Link>{editing ? <><Button tone="secondary" onClick={cancel}>Hủy</Button><Button onClick={requestSave}>Lưu thay đổi</Button></> : <Button onClick={() => { setEditing(true); setNotice(''); }}>Sửa</Button>}</div></div>
    <section className="grid gap-4 rounded-xl border border-line p-4"><h3 className="text-h3">Thông tin cơ sở</h3><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-sm">Tên cơ sở<TextInput aria-label="Tên cơ sở" disabled={!editing} value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} /></label><label className="grid gap-1 text-sm">Địa chỉ<TextInput aria-label="Địa chỉ" disabled={!editing} value={draft.address} onChange={(event) => setDraft({ ...draft, address: event.target.value })} /></label></div><div><span className="text-sm">Tiện ích đề xuất</span><div className="mt-2 flex flex-wrap gap-2">{SUGGESTED_AMENITIES.map((amenity) => { const selected = draft.amenities.includes(amenity); return <button key={amenity} type="button" disabled={!editing} onClick={() => setDraft({ ...draft, amenities: selected ? draft.amenities.filter((item) => item !== amenity) : [...draft.amenities, amenity] })} className={`rounded-full border px-3 py-2 text-sm font-semibold ${selected ? 'bg-brand-navy text-surface' : 'bg-surface text-ink-500'}`}>{selected ? '✓ ' : '+ '}{amenity}</button>; })}</div></div><label className="grid gap-1 text-sm">Tiện ích khác<TextInput aria-label="Tiện ích khác" disabled={!editing} value={draft.amenities.filter((item) => !SUGGESTED_AMENITIES.some((suggested) => suggested === item)).join(', ')} onChange={(event) => setDraft({ ...draft, amenities: [...draft.amenities.filter((item) => SUGGESTED_AMENITIES.some((suggested) => suggested === item)), ...event.target.value.split(',').map((item) => item.trim()).filter(Boolean)] })} /></label></section>
    <section className="grid gap-3 rounded-xl border border-line p-4"><h3 className="text-h3">Vị trí trên bản đồ</h3><LocationPicker disabled={!editing} value={{ lat: draft.lat, lng: draft.lng }} onChange={(next) => setDraft({ ...draft, ...next })} onAddressResolved={(address) => setDraft((current) => ({ ...current, address }))} /></section>
    <section className="grid gap-3 rounded-xl border border-line p-4"><h3 className="text-h3">Ảnh cơ sở</h3><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{existingVenueImages.filter((item) => { const key = keyOf(item); return key && draft.imageKeys.includes(key); }).map((item) => { const key = keyOf(item)!; const url = urlOf(item); return <figure key={key} className="relative overflow-hidden rounded-xl border">{url ? <img src={url} alt="Ảnh cơ sở" className="h-28 w-full object-cover" /> : <div className="grid h-28 place-items-center">🖼️</div>}{editing && <button type="button" onClick={() => setDraft({ ...draft, imageKeys: draft.imageKeys.filter((value) => value !== key) })} className="absolute right-1 top-1 rounded bg-white px-2 py-1 text-xs text-danger">Gỡ</button>}</figure>; })}</div>{editing && <ImageUploadPicker key={`venue-${pickerVersion}`} label="Thêm ảnh cơ sở" authorize={authorizeVenueImage} upload={uploadVenueImage} onUploadedChange={setVenueUploads} />}</section>
    <section className="grid gap-3 rounded-xl border border-line p-4"><div><h3 className="text-h3">Sân con</h3><p className="text-xs text-ink-500">Lịch, giá, quy tắc và ảnh được lưu riêng cho từng sân.</p></div>{editing && <Button className="w-fit" tone="secondary" onClick={() => setDraft({ ...draft, courts: [...draft.courts, { id: `new-${crypto.randomUUID()}`, name: `Sân ${draft.courts.length + 1}`, weekdays: [0,1,2,3,4,5,6], openTime: '08:00', closeTime: '22:00', hourlyPrice: '100000', effectiveFrom: new Date().toISOString().slice(0,10), imageKeys: [] }] })}>+ Thêm sân con</Button>}{draft.courts.map((court) => <CourtEditor key={court.id} court={court} stored={source.courts.find((item) => item.id === court.id)} editing={editing} pickerVersion={pickerVersion} patch={(patch) => patchCourt(court.id, patch)} onUploads={(items) => setCourtUploads((current) => ({ ...current, [court.id]: items }))} />)}</section>
  </SurfaceCard>{error && <p role="alert" className="rounded-xl bg-danger-bg p-3 text-danger">{error}</p>}{notice && <p role="status" className="rounded-xl bg-success-bg p-3 text-success">{notice}</p>}<Modal open={confirming} title="Xác nhận thay đổi" onClose={() => !busy && setConfirming(false)}><p className="text-sm text-ink-600">Các nội dung sau sẽ được cập nhật:</p><ul className="mt-3 grid gap-2">{changes.map((item) => <li key={item} className="rounded-xl bg-canvas p-3 text-sm">• {item}</li>)}</ul><div className="mt-5 flex justify-end gap-2"><Button tone="secondary" disabled={busy} onClick={() => setConfirming(false)}>Quay lại sửa</Button><Button disabled={busy} onClick={() => void save()}>{busy ? 'Đang lưu…' : 'Xác nhận lưu'}</Button></div></Modal></section>;
}

function CourtEditor({ court, stored, editing, pickerVersion, patch, onUploads }: { court: CourtDraft; stored?: ManagedCourt; editing: boolean; pickerVersion: number; patch: (patch: Partial<CourtDraft>) => void; onUploads: (items: UploadImageState[]) => void }) {
  return <article className="grid gap-3 rounded-xl bg-canvas p-4"><label className="grid gap-1 text-sm">Tên sân con<TextInput disabled={!editing} value={court.name} onChange={(event) => patch({ name: event.target.value })} /></label><div className="flex flex-wrap gap-2">{WEEKDAYS.map((label, day) => { const selected = court.weekdays.includes(day); return <button key={day} type="button" disabled={!editing} onClick={() => patch({ weekdays: selected ? court.weekdays.filter((item) => item !== day) : [...court.weekdays, day].sort() })} className={`rounded-full border px-3 py-2 text-sm font-semibold ${selected ? 'bg-brand-navy text-surface' : 'bg-surface text-ink-500'}`}>{selected ? '✓ ' : ''}{label}</button>; })}</div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="grid gap-1 text-sm">Giờ mở<TextInput disabled={!editing} type="time" value={court.openTime} onChange={(event) => patch({ openTime: event.target.value })} /></label><label className="grid gap-1 text-sm">Giờ đóng<TextInput disabled={!editing} type="time" value={court.closeTime} onChange={(event) => patch({ closeTime: event.target.value })} /></label><label className="grid gap-1 text-sm">Giá mỗi giờ<TextInput disabled={!editing} inputMode="numeric" value={formatVnd(court.hourlyPrice)} onChange={(event) => patch({ hourlyPrice: event.target.value.replace(/\D/g, '') })} /></label><label className="grid gap-1 text-sm">Hiệu lực từ<TextInput disabled={!editing} type="date" value={court.effectiveFrom} onChange={(event) => patch({ effectiveFrom: event.target.value })} /></label></div><p className="text-xs text-ink-500">Slot 30 phút, tối thiểu 60 phút; tối đa theo giờ hoạt động.</p><div className="grid grid-cols-2 gap-2 sm:grid-cols-5">{stored?.images.filter((image) => court.imageKeys.includes(image.objectKey)).map((image) => <figure key={image.objectKey} className="relative overflow-hidden rounded-xl border"><img src={image.url} alt={`Ảnh ${court.name}`} className="h-24 w-full object-cover" />{editing && <button type="button" onClick={() => patch({ imageKeys: court.imageKeys.filter((key) => key !== image.objectKey) })} className="absolute right-1 top-1 rounded bg-white px-2 py-1 text-xs text-danger">Gỡ</button>}</figure>)}</div>{editing && <ImageUploadPicker key={`${court.id}-${pickerVersion}`} label={`Thêm ảnh ${court.name}`} maxFiles={Math.max(1, 5 - court.imageKeys.length)} authorize={authorizeVenueImage} upload={uploadVenueImage} onUploadedChange={onUploads} />}</article>;
}
