import { useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { Button } from '../../components/ui'
import { saveBookingRule, savePricing } from '../../lib/venueBookingApi'

export function ManagePricingPage() {
  const [query] = useSearchParams(); const courtId = query.get('courtId') ?? ''
  const [weekday, setWeekday] = useState(1); const [start, setStart] = useState(480); const [end, setEnd] = useState(1320)
  const [price, setPrice] = useState(100000); const [effectiveFrom, setEffectiveFrom] = useState(new Date().toISOString().slice(0, 10))
  const [step, setStep] = useState(30); const [min, setMin] = useState(60); const [max, setMax] = useState(180); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const savePrice = async () => { if (start >= end || price <= 0) return setError('Khung giá bị chồng lấn hoặc không hợp lệ.'); setBusy(true); try { await savePricing(courtId, { effectiveFrom: new Date(`${effectiveFrom}T00:00:00.000Z`).toISOString(), rules: [{ weekday, startMinute: start, endMinute: end, price }] }) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Không thể lưu bảng giá.') } finally { setBusy(false) } }
  const saveRule = async () => { if (step <= 0 || min < step || min % step || max < min || max % step) return setError('Bước, tối thiểu và tối đa phải hợp lệ; min/max chia hết bước.'); setBusy(true); try { await saveBookingRule(courtId, { stepMinutes: step, minDurationMinutes: min, maxDurationMinutes: max }) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Không thể lưu quy tắc.') } finally { setBusy(false) } }
  return <section className="grid max-w-xl gap-3"><h2 className="text-h2">Giá và quy tắc đặt sân</h2><label>Thứ<select value={weekday} onChange={e => setWeekday(Number(e.target.value))}>{[0,1,2,3,4,5,6].map(day => <option value={day} key={day}>{day}</option>)}</select></label><label>Phút bắt đầu<input value={start} onChange={e => setStart(Number(e.target.value))}/></label><label>Phút kết thúc<input value={end} onChange={e => setEnd(Number(e.target.value))}/></label><label>Giá<input aria-label="Giá" value={price} onChange={e => setPrice(Number(e.target.value))}/></label><label>Hiệu lực từ<input type="date" value={effectiveFrom} onChange={e => setEffectiveFrom(e.target.value)}/></label><Button disabled={busy} onClick={() => void savePrice()}>Lưu bảng giá</Button><label>Bước phút<input aria-label="Bước phút" value={step} onChange={e => setStep(Number(e.target.value))}/></label><label>Tối thiểu<input aria-label="Tối thiểu" value={min} onChange={e => setMin(Number(e.target.value))}/></label><label>Tối đa<input aria-label="Tối đa" value={max} onChange={e => setMax(Number(e.target.value))}/></label><Button disabled={busy} onClick={() => void saveRule()}>Lưu quy tắc</Button>{error && <p role="alert">{error}</p>}</section>
}
