import { useEffect, useState } from 'react'
import { Button } from '../../components/ui'
import { cancelMyWithdrawal, createWithdrawal, getMyRevenue, getMyWithdrawals, type RevenueRow, type WithdrawalRow } from '../../lib/financeApi'

const sum = (rows: RevenueRow[], key: 'net' | 'gross') => rows.reduce((total, row) => total + BigInt(row[key]), 0n).toString()
export function ManageFinancePage() {
  const [revenue, setRevenue] = useState<RevenueRow[]>([]); const [withdrawals, setWithdrawals] = useState<WithdrawalRow[]>([]); const [filters, setFilters] = useState({ venueId: '', from: '', to: '' }); const [form, setForm] = useState({ amount: '', bankCode: '', bankAccountNumber: '', bankAccountName: '' }); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const load = async () => { try { const [nextRevenue, nextWithdrawals] = await Promise.all([getMyRevenue(filters), getMyWithdrawals()]); setRevenue(nextRevenue); setWithdrawals(nextWithdrawals) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Không thể tải doanh thu.') } }
  useEffect(() => { void load() }, [])
  const submit = async () => { if (busy || !/^\d+$/.test(form.amount) || Object.values(form).some(value => !value)) return setError('Nhập đủ số tiền và thông tin ngân hàng hợp lệ.'); setBusy(true); try { await createWithdrawal(form); await load() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Không thể tạo yêu cầu rút.') } finally { setBusy(false) } }
  const cancel = async (id: string) => { if (busy) return; setBusy(true); try { await cancelMyWithdrawal(id); await load() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Không thể hủy yêu cầu.') } finally { setBusy(false) } }
  const pending = revenue.filter(row => !row.releasedAt).length; const reserved = revenue.filter(row => row.disputeOpen).length
  return <section className="grid gap-3"><h2 className="text-h2">Doanh thu và rút tiền</h2><div className="grid grid-cols-3 gap-2"><p>Pending: {pending}</p><p>Available: {sum(revenue.filter(row => Boolean(row.releasedAt) && !row.disputeOpen), 'net')}</p><p>Reserved: {reserved}</p></div><input aria-label="Lọc venue" value={filters.venueId} onChange={e => setFilters({ ...filters, venueId: e.target.value })}/><input type="date" aria-label="Từ ngày" value={filters.from} onChange={e => setFilters({ ...filters, from: e.target.value })}/><input type="date" aria-label="Đến ngày" value={filters.to} onChange={e => setFilters({ ...filters, to: e.target.value })}/><Button disabled={busy} onClick={() => void load()}>Lọc doanh thu</Button>{(['amount','bankCode','bankAccountNumber','bankAccountName'] as const).map(key => <input key={key} aria-label={key} value={form[key]} onChange={e => setForm({ ...form, [key]: e.target.value })}/>)}<Button disabled={busy} onClick={() => void submit()}>Gửi yêu cầu rút</Button>{withdrawals.filter(row => row.status === 'pending').map(row => <div key={row.id}>{row.amount}<Button disabled={busy} size="sm" onClick={() => void cancel(row.id)}>Hủy yêu cầu</Button></div>)}{error && <p role="alert">{error}</p>}</section>
}
