import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { Button } from '../../components/ui'
import { addManagedCourt, deactivateManagedCourt, getMyManagedVenue, updateManagedVenue, type ManagedVenue } from '../../lib/venueBookingApi'
export function ManageVenueDetailPage() {
  const { venueId = '' } = useParams(); const [venue, setVenue] = useState<ManagedVenue>(); const [courtName, setCourtName] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const load = async () => { try { setVenue(await getMyManagedVenue(venueId)) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Không thể tải cơ sở.') } }
  useEffect(() => { void load() }, [venueId])
  const saveVenue = async () => { if (!venue || busy) return; setBusy(true); try { await updateManagedVenue(venueId, { name: venue.name, address: venue.address, lat: venue.lat, lng: venue.lng, amenities: venue.amenities, images: venue.images }); await load() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Không thể cập nhật cơ sở.') } finally { setBusy(false) } }
  const addCourt = async () => { if (!courtName.trim() || busy) return; setBusy(true); try { await addManagedCourt(venueId, courtName.trim()); setCourtName(''); await load() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Không thể thêm sân con.') } finally { setBusy(false) } }
  const deactivate = async (id: string) => { if (!window.confirm('Xác nhận ngưng hoạt động sân này?')) return; setBusy(true); try { await deactivateManagedCourt(id); await load() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Không thể ngưng sân; kiểm tra các booking xung đột.') } finally { setBusy(false) } }
  if (!venue) return <p>{error || 'Đang tải cơ sở...'}</p>
  return <section className="grid gap-3"><h2 className="text-h2">Chi tiết cơ sở</h2><label>Tên cơ sở<input aria-label="Tên cơ sở" value={venue.name} onChange={e => setVenue({ ...venue, name: e.target.value })}/></label><label>Địa chỉ<input aria-label="Địa chỉ" value={venue.address} onChange={e => setVenue({ ...venue, address: e.target.value })}/></label><label>Vĩ độ<input aria-label="Vĩ độ" value={venue.lat} onChange={e => setVenue({ ...venue, lat: Number(e.target.value) })}/></label><label>Kinh độ<input aria-label="Kinh độ" value={venue.lng} onChange={e => setVenue({ ...venue, lng: Number(e.target.value) })}/></label><Button disabled={busy} onClick={() => void saveVenue()}>Lưu thay đổi</Button><label>Tên sân con<input aria-label="Tên sân con" value={courtName} onChange={e => setCourtName(e.target.value)}/></label><Button disabled={busy} onClick={() => void addCourt()}>Thêm sân con</Button>{venue.courts.map(c => <div key={c.id}>{c.name} <Link to={`/manage/venues/${venueId}/schedule?courtId=${c.id}`}>Lịch</Link> <Link to={`/manage/venues/${venueId}/pricing?courtId=${c.id}`}>Giá</Link>{c.active && <Button disabled={busy} size="sm" tone="secondary" onClick={() => void deactivate(c.id)}>Ngưng hoạt động</Button>}</div>)}{error && <p role="alert">{error}</p>}</section>
}
