import { useState } from 'react';
import { Badge, Button, Modal, TextInput } from '../../components/ui';
import { formatMoneyVnd } from '../../lib/formatters.js';

export function WithdrawalModal({ open, available, active, busy, onClose, onSubmit, onCancel }: { open: boolean; available: string; active: { id: string; transferCode: string; amount: string; status: string } | null; busy: boolean; onClose: () => void; onSubmit: (body: { amount: string; bankCode: string; bankAccountNumber: string; bankAccountName: string }) => void; onCancel: (id: string) => void }) {
  const [form, setForm] = useState({ amount: '', bankCode: '', bankAccountNumber: '', bankAccountName: '' });
  const [error, setError] = useState('');
  const submit = () => { const clean = { amount: form.amount.replace(/\D/g, ''), bankCode: form.bankCode.trim(), bankAccountNumber: form.bankAccountNumber.trim(), bankAccountName: form.bankAccountName.trim() }; if (!clean.amount || BigInt(clean.amount) < 10_000n || Object.values(clean).some((value) => !value)) { setError('Nhập đủ thông tin và số tiền từ 10.000đ.'); return; } if (BigInt(clean.amount) > BigInt(available)) { setError('Số tiền rút vượt quá số dư khả dụng.'); return; } onSubmit(clean); };
  return <Modal open={open} title={active ? 'Yêu cầu rút tiền đang xử lý' : 'Rút tiền'} onClose={onClose}>
    {active ? <div className="grid gap-4"><div className="rounded-2xl bg-canvas p-4"><p className="text-caption text-ink-500">{active.transferCode}</p><p className="mt-1 text-xl font-bold text-figures">{formatMoneyVnd(active.amount)}</p><Badge tone="warning">Đang chờ xử lý</Badge></div><p className="text-sm text-ink-500">Bạn chỉ có thể tạo yêu cầu mới sau khi yêu cầu này hoàn tất hoặc bị hủy.</p>{active.status === 'pending' && <Button tone="danger" disabled={busy} onClick={() => onCancel(active.id)}>Hủy yêu cầu</Button>}</div> : <div className="grid gap-4"><p className="text-sm text-ink-500">Khả dụng: <strong className="text-figures text-ink-900">{formatMoneyVnd(available)}</strong></p><label className="grid gap-1 text-sm font-medium">Số tiền rút<div className="flex gap-2"><TextInput aria-label="Số tiền rút" inputMode="numeric" value={form.amount ? formatMoneyVnd(form.amount) : ''} onChange={(event) => setForm({ ...form, amount: event.target.value.replace(/\D/g, '') })} /><Button tone="secondary" size="sm" onClick={() => setForm({ ...form, amount: available })}>Rút toàn bộ</Button></div></label><label className="grid gap-1 text-sm font-medium">Mã ngân hàng<TextInput aria-label="Mã ngân hàng" value={form.bankCode} onChange={(event) => setForm({ ...form, bankCode: event.target.value })} /></label><label className="grid gap-1 text-sm font-medium">Số tài khoản nhận<TextInput aria-label="Số tài khoản nhận" inputMode="numeric" value={form.bankAccountNumber} onChange={(event) => setForm({ ...form, bankAccountNumber: event.target.value })} /></label><label className="grid gap-1 text-sm font-medium">Tên chủ tài khoản<TextInput aria-label="Tên chủ tài khoản" value={form.bankAccountName} onChange={(event) => setForm({ ...form, bankAccountName: event.target.value })} /></label>{error && <p role="alert" className="text-sm text-danger">{error}</p>}<Button disabled={busy} onClick={submit}>{busy ? 'Đang gửi…' : 'Xác nhận yêu cầu rút'}</Button></div>}
  </Modal>;
}
